<template>
  <div>
    <the-header></the-header>
    <the-sidebar @toggle-sidebar="handleToggle"></the-sidebar>
    <salary-composition-list :isToggle="isToggle"></salary-composition-list>
    <ms-toast></ms-toast>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import TheHeader from '@/layouts/TheHeader.vue'
import TheSidebar from '@/layouts/TheSidebar.vue'
import SalaryCompositionList from '@/views/salary-composition/Index.vue'
import MsToast from '@/components/control/MsToast.vue'

const isToggle = ref(false)

const handleToggle = (value) => {
  isToggle.value = value
}

const employeeData = [
  {
    id: 1,
    name: 'Nguyễn Văn An',
    dob: '12/03/1998',
    gender: 'Nam',
    region: 'Hà Nội',
    phone: '0912345678',
    email: 'an.nguyen@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 2,
    name: 'Trần Thị Bình',
    dob: '25/07/1999',
    gender: 'Nữ',
    region: 'TP Hồ Chí Minh',
    phone: '0987654321',
    email: 'binh.tran@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 3,
    name: 'Lê Quốc Cường',
    dob: '02/11/1997',
    gender: 'Nam',
    region: 'Đà Nẵng',
    phone: '0903123456',
    email: 'cuong.le@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 4,
    name: 'Phạm Thị Diễm',
    dob: '19/05/2000',
    gender: 'Nữ',
    region: 'Cần Thơ',
    phone: '0938123456',
    email: 'diem.pham@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 5,
    name: 'Hoàng Minh Đức',
    dob: '08/01/1996',
    gender: 'Nam',
    region: 'Hải Phòng',
    phone: '0977123456',
    email: 'duc.hoang@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 6,
    name: 'Vũ Thị Em',
    dob: '30/09/1998',
    gender: 'Nữ',
    region: 'Nam Định',
    phone: '0945123456',
    email: 'em.vu@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 7,
    name: 'Đặng Quốc Phong',
    dob: '14/02/1997',
    gender: 'Nam',
    region: 'Nghệ An',
    phone: '0968123456',
    email: 'phong.dang@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 8,
    name: 'Bùi Thị Hạnh',
    dob: '22/06/2001',
    gender: 'Nữ',
    region: 'Thanh Hóa',
    phone: '0918123456',
    email: 'hanh.bui@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 9,
    name: 'Ngô Văn Khoa',
    dob: '05/12/1995',
    gender: 'Nam',
    region: 'Bình Dương',
    phone: '0929123456',
    email: 'khoa.ngo@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 10,
    name: 'Đỗ Thị Lan',
    dob: '17/04/1999',
    gender: 'Nữ',
    region: 'Bắc Ninh',
    phone: '0956123456',
    email: 'lan.do@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 11,
    name: 'Phan Văn Minh',
    dob: '09/08/1996',
    gender: 'Nam',
    region: 'Quảng Ninh',
    phone: '0908123456',
    email: 'minh.phan@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 12,
    name: 'Lý Thị Ngọc',
    dob: '28/10/2000',
    gender: 'Nữ',
    region: 'Khánh Hòa',
    phone: '0933123456',
    email: 'ngoc.ly@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 13,
    name: 'Trương Quốc Nam',
    dob: '11/01/1998',
    gender: 'Nam',
    region: 'Long An',
    phone: '0973123456',
    email: 'nam.truong@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 14,
    name: 'Mai Thị Oanh',
    dob: '03/03/2002',
    gender: 'Nữ',
    region: 'Thái Bình',
    phone: '0949123456',
    email: 'oanh.mai@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 15,
    name: 'Nguyễn Hoàng Phúc',
    dob: '21/07/1997',
    gender: 'Nam',
    region: 'TP Hồ Chí Minh',
    phone: '0983123456',
    email: 'phuc.nguyen@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 16,
    name: 'Trần Minh Tuấn',
    dob: '03/11/1996',
    gender: 'Nam',
    region: 'Hà Nội',
    phone: '0978123456',
    email: 'tuan.tran@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 17,
    name: 'Lê Thị Ngọc Anh',
    dob: '15/04/1998',
    gender: 'Nữ',
    region: 'Đà Nẵng',
    phone: '0912345678',
    email: 'anh.le@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 18,
    name: 'Phạm Quốc Huy',
    dob: '09/09/1995',
    gender: 'Nam',
    region: 'Hải Phòng',
    phone: '0909988776',
    email: 'huy.pham@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 19,
    name: 'Nguyễn Thị Mai',
    dob: '28/01/1999',
    gender: 'Nữ',
    region: 'Cần Thơ',
    phone: '0933445566',
    email: 'mai.nguyen@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 20,
    name: 'Võ Thanh Long',
    dob: '17/06/1994',
    gender: 'Nam',
    region: 'Bình Dương',
    phone: '0966778899',
    email: 'long.vo@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 21,
    name: 'Đặng Thị Hồng Nhung',
    dob: '02/02/2000',
    gender: 'Nữ',
    region: 'TP Hồ Chí Minh',
    phone: '0988112233',
    email: 'nhung.dang@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 22,
    name: 'Bùi Anh Khoa',
    dob: '11/08/1997',
    gender: 'Nam',
    region: 'Huế',
    phone: '0944556677',
    email: 'khoa.bui@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 23,
    name: 'Hoàng Thị Thu Trang',
    dob: '30/12/1996',
    gender: 'Nữ',
    region: 'Nam Định',
    phone: '0922334455',
    email: 'trang.hoang@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 24,
    name: 'Ngô Văn Khánh',
    dob: '14/05/1993',
    gender: 'Nam',
    region: 'Quảng Ninh',
    phone: '0977554433',
    email: 'khanh.ngo@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 25,
    name: 'Trịnh Thị Lan',
    dob: '19/10/1998',
    gender: 'Nữ',
    region: 'Thanh Hóa',
    phone: '0901122334',
    email: 'lan.trinh@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 26,
    name: 'Đỗ Đức Mạnh',
    dob: '07/07/1995',
    gender: 'Nam',
    region: 'Hà Nam',
    phone: '0933111222',
    email: 'manh.do@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 27,
    name: 'Phan Thị Bích Ngọc',
    dob: '25/03/1999',
    gender: 'Nữ',
    region: 'Nha Trang',
    phone: '0966889900',
    email: 'ngoc.phan@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 28,
    name: 'Lý Quốc Bảo',
    dob: '01/01/1994',
    gender: 'Nam',
    region: 'An Giang',
    phone: '0911998877',
    email: 'bao.ly@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 29,
    name: 'Nguyễn Thế Anh',
    dob: '18/09/1997',
    gender: 'Nam',
    region: 'Vĩnh Phúc',
    phone: '0987665544',
    email: 'anh.nguyen@gmail.com',
    country: 'Việt Nam',
  },
  {
    id: 30,
    name: 'Tạ Mỹ Linh',
    dob: '22/02/2001',
    gender: 'Nữ',
    region: 'Bắc Ninh',
    phone: '0955332211',
    email: 'linh.ta@gmail.com',
    country: 'Việt Nam',
  },
]

onMounted(() => {
  localStorage.setItem('key_local_employee', JSON.stringify(employeeData))
})
</script>
<style>
@import './assets/css/icon.css';
@import './assets/css/variable.css';
@import './assets/base.css';
@import './assets/css/components/input.css';
</style>
